name: Universal Builder

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      intent:
        description: 'Build intent'
        required: true
      value_threshold:
        description: 'Value threshold for this task'
        required: false
        default: '50'
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes (reduced frequency to avoid API rate limits)

jobs:
  universal-builder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build project
      run: dotnet build --configuration Release --no-restore
        
    - name: Set environment variables
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        VALUE_THRESHOLD: ${{ github.event.inputs.value_threshold || secrets.DEFAULT_VALUE_THRESHOLD || '50' }}
      run: |
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV
        echo "AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY" >> $GITHUB_ENV
        echo "AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT" >> $GITHUB_ENV
        echo "VALUE_THRESHOLD=$VALUE_THRESHOLD" >> $GITHUB_ENV
        
    - name: Determine intent
      id: determine_intent
      run: |
        if [ "${{ github.event_name }}" == "issues" ]; then
          INTENT=$(echo "${{ github.event.issue.title }}" | tr -d '\n')
          VALUE_THRESHOLD="${{ secrets.DEFAULT_VALUE_THRESHOLD || '50' }}"
          echo "INTENT=$INTENT" >> $GITHUB_ENV
          echo "VALUE_THRESHOLD=$VALUE_THRESHOLD" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          INTENT="${{ github.event.inputs.intent }}"
          VALUE_THRESHOLD="${{ github.event.inputs.value_threshold || secrets.DEFAULT_VALUE_THRESHOLD || '50' }}"
          echo "INTENT=$INTENT" >> $GITHUB_ENV
          echo "VALUE_THRESHOLD=$VALUE_THRESHOLD" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "schedule" ]; then
          # For scheduled runs, check if there's any pending work or if system should self-evolve
          # This allows the system to decide what to do on its own
          echo "Scheduled run - Universal Builder will check for pending work or self-evolve"
          # Default to self-evolution if no specific task is found
          INTENT="Self-evolve and improve Universal Builder capabilities"
          VALUE_THRESHOLD="${{ secrets.DEFAULT_VALUE_THRESHOLD || '50' }}"
          echo "INTENT=$INTENT" >> $GITHUB_ENV
          echo "VALUE_THRESHOLD=$VALUE_THRESHOLD" >> $GITHUB_ENV
        fi
        
    - name: Run Universal Builder
      run: |
        echo "Running with intent: $INTENT"
        echo "Value threshold: $VALUE_THRESHOLD"
        dotnet run --project . --configuration Release -- "$INTENT" "$VALUE_THRESHOLD"
        
    - name: Create PR for self-evolution (if changes detected)
      if: success()
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          PR_BRANCH="self-evolution-$(date +%Y%m%d%H%M%S)"
          git config --global user.name "Universal Builder"
          git config --global user.email "universal-builder@noreply.github.com"
          git checkout -b $PR_BRANCH
          git add .
          git commit -m "Self-evolution: Improvements from latest run"
          git push origin $PR_BRANCH
          
          # Use GitHub CLI to create PR
          gh pr create --title "Self-evolution: Improvements from latest run" \
                       --body "This PR contains self-improvements generated by the Universal Builder system based on the latest execution. Review the changes and merge if they enhance the system." \
                       --base main \
                       --head $PR_BRANCH
        else
          echo "No changes detected, skipping PR creation"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 